CREATE OR REPLACE FUNCTION trg_upper_string()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.ename := UPPER(NEW.ename);
    RETURN NEW;
END;
$$;

CREATE TRIGGER UPPER_STRING
BEFORE INSERT OR UPDATE ON emp
FOR EACH ROW
EXECUTE FUNCTION trg_upper_string();

