CREATE TABLE Dept (
  deptno DECIMAL(2,0) NOT NULL,
  dname VARCHAR(14) NOT NULL,
  loc VARCHAR(13) NOT NULL
);

INSERT INTO Dept (deptno, dname, loc) VALUES
(10, 'ACCOUNTING', 'NEW YORK'),
(20, 'RESEARCH', 'DALLAS'),
(30, 'SALES', 'CHICAGO'),
(40, 'OPERATIONS', 'BOSTON');

SELECT * FROM Dept;
